name: LintingAndTesting

on: 
  - workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
  
  lint:
    needs: [setup]
    steps:
      - run: npm run lint
  
  test:
    needs: [setup]
    steps:
      - name: unit tests
      - run: npm run test
      - name: e2e tests
      - run: npm run test:e2e

