name: Pull Request Testing

on: 
  pull_request:
    branches: 
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codefortulsa/website/.github/workflows/lint-and-test/