name: Pull Request Testing

on: 
  pull_request:
    branches: 
      - 'feature/cicd-test'
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '16'
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: prod build
        run: yarn build

  e2e tests: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      run: yarn test:e2e
